log:
  level: "INFO" # optional, log level, possible values are DEBUG, INFO, WARNING, ERROR, CRITICAL
  path: "~/foo.log" # optional; alternatively, use environment variable T2M_LOG_PATH
  count: 0 # optional; number of saved old log files. Zero does not delete any old log file.
tibber:
  token: "tibbertoken" # alternatively, use environment variable T2M_TIBBER_TOKEN
  home: "homeid" # alternatively, use environment variable T2M_TIBBER_TOKEN
  api_timeout: 5 # optional, timeout of the live data availability check (in seconds)
  websocket_timeout: 30 # optional, timeout of the websocket connect (in seconds)
mqtt:
  server1: # a name of your choise, will be shown in the logs
    host: "127.0.0.1:1883"
    topic: "foo/abc"
  server2:
    host: "1.2.3.4:8883"
    topic: "bar/def"
    ca: "path/to/cert/ca/file.crt" # optional, onyl used for TLS connection
    tls_insecure: false # optional, must be set to true for self signed certificates
    user: "username" # optional, only for auth via username + password
    password: "password" # optional, only for auth via username + password
    public_key: "path/to/cert/public/key/file.crt" # optional, only for auth via certificate
    private_key: "path/to/cert/private/key/file.crt" # optional, only for auth via certificate
watchdog:
  tolerance: 20 # maximum time between two live data packets (in seconds)
  timeout: 5 # delay between losing live data and reconnect (in seconds)
  maximum_timeout: 60 # maximum delay between losing live data and reconnect (in seconds)